/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsBoolean,
  IsOptional,
  ValidateNested,
  IsString,
} from "class-validator";
import { CustomerCreateNestedManyWithoutEntitiesInput } from "./CustomerCreateNestedManyWithoutEntitiesInput";
import { Type } from "class-transformer";
import { IsJSONValue } from "@app/custom-validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { ItemCreateNestedManyWithoutEntitiesInput } from "./ItemCreateNestedManyWithoutEntitiesInput";
import { UserCreateNestedManyWithoutEntitiesInput } from "./UserCreateNestedManyWithoutEntitiesInput";

@InputType()
class EntityCreateInput {
  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  accrualMethod?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => CustomerCreateNestedManyWithoutEntitiesInput,
  })
  @ValidateNested()
  @Type(() => CustomerCreateNestedManyWithoutEntitiesInput)
  @IsOptional()
  @Field(() => CustomerCreateNestedManyWithoutEntitiesInput, {
    nullable: true,
  })
  customers?: CustomerCreateNestedManyWithoutEntitiesInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  info?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => ItemCreateNestedManyWithoutEntitiesInput,
  })
  @ValidateNested()
  @Type(() => ItemCreateNestedManyWithoutEntitiesInput)
  @IsOptional()
  @Field(() => ItemCreateNestedManyWithoutEntitiesInput, {
    nullable: true,
  })
  items?: ItemCreateNestedManyWithoutEntitiesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserCreateNestedManyWithoutEntitiesInput,
  })
  @ValidateNested()
  @Type(() => UserCreateNestedManyWithoutEntitiesInput)
  @IsOptional()
  @Field(() => UserCreateNestedManyWithoutEntitiesInput, {
    nullable: true,
  })
  users?: UserCreateNestedManyWithoutEntitiesInput;
}

export { EntityCreateInput as EntityCreateInput };
