/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsBoolean,
  IsOptional,
  ValidateNested,
  IsString,
} from "class-validator";
import { CustomerUpdateManyWithoutEntitiesInput } from "./CustomerUpdateManyWithoutEntitiesInput";
import { Type } from "class-transformer";
import { IsJSONValue } from "@app/custom-validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { ItemUpdateManyWithoutEntitiesInput } from "./ItemUpdateManyWithoutEntitiesInput";
import { LedgerUpdateManyWithoutEntitiesInput } from "./LedgerUpdateManyWithoutEntitiesInput";
import { UserUpdateManyWithoutEntitiesInput } from "./UserUpdateManyWithoutEntitiesInput";

@InputType()
class EntityUpdateInput {
  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  accrualMethod?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => CustomerUpdateManyWithoutEntitiesInput,
  })
  @ValidateNested()
  @Type(() => CustomerUpdateManyWithoutEntitiesInput)
  @IsOptional()
  @Field(() => CustomerUpdateManyWithoutEntitiesInput, {
    nullable: true,
  })
  customers?: CustomerUpdateManyWithoutEntitiesInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  info?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => ItemUpdateManyWithoutEntitiesInput,
  })
  @ValidateNested()
  @Type(() => ItemUpdateManyWithoutEntitiesInput)
  @IsOptional()
  @Field(() => ItemUpdateManyWithoutEntitiesInput, {
    nullable: true,
  })
  items?: ItemUpdateManyWithoutEntitiesInput;

  @ApiProperty({
    required: false,
    type: () => LedgerUpdateManyWithoutEntitiesInput,
  })
  @ValidateNested()
  @Type(() => LedgerUpdateManyWithoutEntitiesInput)
  @IsOptional()
  @Field(() => LedgerUpdateManyWithoutEntitiesInput, {
    nullable: true,
  })
  ledgers?: LedgerUpdateManyWithoutEntitiesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserUpdateManyWithoutEntitiesInput,
  })
  @ValidateNested()
  @Type(() => UserUpdateManyWithoutEntitiesInput)
  @IsOptional()
  @Field(() => UserUpdateManyWithoutEntitiesInput, {
    nullable: true,
  })
  users?: UserUpdateManyWithoutEntitiesInput;
}

export { EntityUpdateInput as EntityUpdateInput };
