/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsBoolean,
  IsOptional,
  ValidateNested,
  IsString,
} from "class-validator";
import { ClientUpdateManyWithoutEntitiesInput } from "./ClientUpdateManyWithoutEntitiesInput";
import { Type } from "class-transformer";
import { IsJSONValue } from "@app/custom-validators";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { ItemUpdateManyWithoutEntitiesInput } from "./ItemUpdateManyWithoutEntitiesInput";
import { UserWhereUniqueInput } from "../../user/base/UserWhereUniqueInput";

@InputType()
class EntityUpdateInput {
  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  accrualMethod?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => ClientUpdateManyWithoutEntitiesInput,
  })
  @ValidateNested()
  @Type(() => ClientUpdateManyWithoutEntitiesInput)
  @IsOptional()
  @Field(() => ClientUpdateManyWithoutEntitiesInput, {
    nullable: true,
  })
  customers?: ClientUpdateManyWithoutEntitiesInput;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  info?: InputJsonValue;

  @ApiProperty({
    required: false,
    type: () => ItemUpdateManyWithoutEntitiesInput,
  })
  @ValidateNested()
  @Type(() => ItemUpdateManyWithoutEntitiesInput)
  @IsOptional()
  @Field(() => ItemUpdateManyWithoutEntitiesInput, {
    nullable: true,
  })
  items?: ItemUpdateManyWithoutEntitiesInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => UserWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => UserWhereUniqueInput)
  @IsOptional()
  @Field(() => UserWhereUniqueInput, {
    nullable: true,
  })
  uid?: UserWhereUniqueInput | null;
}

export { EntityUpdateInput as EntityUpdateInput };
