/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { LedgerService } from "../ledger.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { LedgerCreateInput } from "./LedgerCreateInput";
import { LedgerWhereInput } from "./LedgerWhereInput";
import { LedgerWhereUniqueInput } from "./LedgerWhereUniqueInput";
import { LedgerFindManyArgs } from "./LedgerFindManyArgs";
import { LedgerUpdateInput } from "./LedgerUpdateInput";
import { Ledger } from "./Ledger";
import { JournalFindManyArgs } from "../../journal/base/JournalFindManyArgs";
import { Journal } from "../../journal/base/Journal";
import { JournalWhereUniqueInput } from "../../journal/base/JournalWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class LedgerControllerBase {
  constructor(
    protected readonly service: LedgerService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Ledger })
  @nestAccessControl.UseRoles({
    resource: "Ledger",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: LedgerCreateInput,
  })
  async create(@common.Body() data: LedgerCreateInput): Promise<Ledger> {
    return await this.service.create({
      data: {
        ...data,

        entity: data.entity
          ? {
              connect: data.entity,
            }
          : undefined,
      },
      select: {
        createdAt: true,

        entity: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Ledger] })
  @ApiNestedQuery(LedgerFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Ledger",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<Ledger[]> {
    const args = plainToClass(LedgerFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        createdAt: true,

        entity: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Ledger })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Ledger",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: LedgerWhereUniqueInput
  ): Promise<Ledger | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        createdAt: true,

        entity: {
          select: {
            id: true,
          },
        },

        id: true,
        name: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Ledger })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Ledger",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  @swagger.ApiBody({
    type: LedgerUpdateInput,
  })
  async update(
    @common.Param() params: LedgerWhereUniqueInput,
    @common.Body() data: LedgerUpdateInput
  ): Promise<Ledger | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          entity: data.entity
            ? {
                connect: data.entity,
              }
            : undefined,
        },
        select: {
          createdAt: true,

          entity: {
            select: {
              id: true,
            },
          },

          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Ledger })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Ledger",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: LedgerWhereUniqueInput
  ): Promise<Ledger | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          createdAt: true,

          entity: {
            select: {
              id: true,
            },
          },

          id: true,
          name: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/journals")
  @ApiNestedQuery(JournalFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Journal",
    action: "read",
    possession: "any",
  })
  async findManyJournals(
    @common.Req() request: Request,
    @common.Param() params: LedgerWhereUniqueInput
  ): Promise<Journal[]> {
    const query = plainToClass(JournalFindManyArgs, request.query);
    const results = await this.service.findJournals(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        ledger: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/journals")
  @nestAccessControl.UseRoles({
    resource: "Ledger",
    action: "update",
    possession: "any",
  })
  async connectJournals(
    @common.Param() params: LedgerWhereUniqueInput,
    @common.Body() body: JournalWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      journals: {
        connect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/journals")
  @nestAccessControl.UseRoles({
    resource: "Ledger",
    action: "update",
    possession: "any",
  })
  async updateJournals(
    @common.Param() params: LedgerWhereUniqueInput,
    @common.Body() body: JournalWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      journals: {
        set: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/journals")
  @nestAccessControl.UseRoles({
    resource: "Ledger",
    action: "update",
    possession: "any",
  })
  async disconnectJournals(
    @common.Param() params: LedgerWhereUniqueInput,
    @common.Body() body: JournalWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      journals: {
        disconnect: body,
      },
    };
    await this.service.update({
      where: params,
      data,
      select: { id: true },
    });
  }
}
