/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { InvoiceModelService } from "../invoiceModel.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { InvoiceModelCreateInput } from "./InvoiceModelCreateInput";
import { InvoiceModelWhereInput } from "./InvoiceModelWhereInput";
import { InvoiceModelWhereUniqueInput } from "./InvoiceModelWhereUniqueInput";
import { InvoiceModelFindManyArgs } from "./InvoiceModelFindManyArgs";
import { InvoiceModelUpdateInput } from "./InvoiceModelUpdateInput";
import { InvoiceModel } from "./InvoiceModel";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class InvoiceModelControllerBase {
  constructor(
    protected readonly service: InvoiceModelService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: InvoiceModel })
  @nestAccessControl.UseRoles({
    resource: "InvoiceModel",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async create(
    @common.Body() data: InvoiceModelCreateInput
  ): Promise<InvoiceModel> {
    return await this.service.create({
      data: {
        ...data,

        customer: data.customer
          ? {
              connect: data.customer,
            }
          : undefined,

        entity: data.entity
          ? {
              connect: data.entity,
            }
          : undefined,

        item: data.item
          ? {
              connect: data.item,
            }
          : undefined,

        ledger: data.ledger
          ? {
              connect: data.ledger,
            }
          : undefined,
      },
      select: {
        amountDue: true,
        amountPaid: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        entity: {
          select: {
            id: true,
          },
        },

        id: true,
        info: true,
        invoiceNumber: true,
        invoiceStatus: true,

        item: {
          select: {
            id: true,
          },
        },

        ledger: {
          select: {
            id: true,
          },
        },

        pricePerUnit: true,
        quantity: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [InvoiceModel] })
  @ApiNestedQuery(InvoiceModelFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "InvoiceModel",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findMany(@common.Req() request: Request): Promise<InvoiceModel[]> {
    const args = plainToClass(InvoiceModelFindManyArgs, request.query);
    return this.service.findMany({
      ...args,
      select: {
        amountDue: true,
        amountPaid: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        entity: {
          select: {
            id: true,
          },
        },

        id: true,
        info: true,
        invoiceNumber: true,
        invoiceStatus: true,

        item: {
          select: {
            id: true,
          },
        },

        ledger: {
          select: {
            id: true,
          },
        },

        pricePerUnit: true,
        quantity: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: InvoiceModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "InvoiceModel",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async findOne(
    @common.Param() params: InvoiceModelWhereUniqueInput
  ): Promise<InvoiceModel | null> {
    const result = await this.service.findOne({
      where: params,
      select: {
        amountDue: true,
        amountPaid: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        entity: {
          select: {
            id: true,
          },
        },

        id: true,
        info: true,
        invoiceNumber: true,
        invoiceStatus: true,

        item: {
          select: {
            id: true,
          },
        },

        ledger: {
          select: {
            id: true,
          },
        },

        pricePerUnit: true,
        quantity: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: InvoiceModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "InvoiceModel",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async update(
    @common.Param() params: InvoiceModelWhereUniqueInput,
    @common.Body() data: InvoiceModelUpdateInput
  ): Promise<InvoiceModel | null> {
    try {
      return await this.service.update({
        where: params,
        data: {
          ...data,

          customer: data.customer
            ? {
                connect: data.customer,
              }
            : undefined,

          entity: data.entity
            ? {
                connect: data.entity,
              }
            : undefined,

          item: data.item
            ? {
                connect: data.item,
              }
            : undefined,

          ledger: data.ledger
            ? {
                connect: data.ledger,
              }
            : undefined,
        },
        select: {
          amountDue: true,
          amountPaid: true,
          createdAt: true,

          customer: {
            select: {
              id: true,
            },
          },

          entity: {
            select: {
              id: true,
            },
          },

          id: true,
          info: true,
          invoiceNumber: true,
          invoiceStatus: true,

          item: {
            select: {
              id: true,
            },
          },

          ledger: {
            select: {
              id: true,
            },
          },

          pricePerUnit: true,
          quantity: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: InvoiceModel })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "InvoiceModel",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async delete(
    @common.Param() params: InvoiceModelWhereUniqueInput
  ): Promise<InvoiceModel | null> {
    try {
      return await this.service.delete({
        where: params,
        select: {
          amountDue: true,
          amountPaid: true,
          createdAt: true,

          customer: {
            select: {
              id: true,
            },
          },

          entity: {
            select: {
              id: true,
            },
          },

          id: true,
          info: true,
          invoiceNumber: true,
          invoiceStatus: true,

          item: {
            select: {
              id: true,
            },
          },

          ledger: {
            select: {
              id: true,
            },
          },

          pricePerUnit: true,
          quantity: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
